version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd frontend
      - npm install

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync dist s3://a081024-angular-website --delete
